-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "qrPlacementX" DOUBLE PRECISION DEFAULT 100,
ADD COLUMN     "qrPlacementY" DOUBLE PRECISION DEFAULT 100,
ADD COLUMN     "qrSize" INTEGER DEFAULT 200,
ADD COLUMN     "templateCardUrl" TEXT;
